import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_STORAGE_KEY = "nesabaLanguage";

const translations = {
  id: {
    brandName: "Nesaba Learn",
    nav: {
      login: "Login",
      signUp: "Sign Up",
      languageToggle: "Ganti Bahasa",
    },
    auth: {
      login: {
        title: "Masuk ke akun Anda",
        subtitle: "Masukkan email dan password untuk masuk",
        emailLabel: "Email",
        emailPlaceholder: "Masukkan email Anda",
        passwordLabel: "Password",
        passwordPlaceholder: "Masukkan password",
        forgotPassword: "Lupa password?",
        submit: "Login",
        footer: "Belum punya akun?",
        footerLink: "Daftar Sekarang",
      },
      register: {
        title: "Buat akun Anda",
        subtitle: "Isi data berikut untuk mendaftar",
        firstNameLabel: "Nama depan",
        firstNamePlaceholder: "Masukkan nama depan",
        lastNameLabel: "Nama belakang",
        lastNamePlaceholder: "Masukkan nama belakang",
        emailLabel: "Email",
        emailPlaceholder: "Masukkan email",
        passwordLabel: "Password",
        passwordPlaceholder: "Buat password",
        confirmPasswordLabel: "Konfirmasi password",
        confirmPasswordPlaceholder: "Ulangi password",
        submit: "Daftar",
        footer: "Sudah punya akun?",
        footerLink: "Log in",
      },
      forgot: {
        title: "Lupa password?",
        subtitle: "Masukkan email Anda dan kami akan mengirimkan link reset password",
        emailLabel: "Email",
        emailPlaceholder: "Masukkan email",
        submit: "Kirim Link Reset",
        submitBusy: "Mengirim...",
        footer: "Sudah ingat password?",
        footerLink: "Log in",
      },
    },
    hero: {
      title: ["Platform Pembelajaran Terbaik", "Penulisan Artikel & Jurnal Ilmiah"],
      description:
        "Tingkatkan keterampilan menulis artikel ilmiah dan mengelola jurnal OJS melalui platform pembelajaran modern. Belajar kapan saja, di mana saja dengan video, quiz, meet, absensi, dan materi yang interaktif.",
      cta: "Mulai Belajar Sekarang",
      imageAlt: "Belajar Online",
    },
    overview: {
      title: "Pembelajaran Artikel & Jurnal Ilmiah, Lebih Mudah dan Terstruktur",
      description:
        "NesabaLearn menghadirkan LMS interaktif untuk membantu penulis, dosen, guru, dan mahasiswa memahami alur penulisan artikel, publikasi jurnal, hingga pengelolaan OJS. Semua materi disusun sistematis, mudah dipahami, dan didukung fitur digital yang lengkap.",
      cta: "Lihat Program Pelatihan",
    },
    howItWorks: {
      title: "Cara Menggunakan NesabaLearn",
      description:
        "Ikuti langkah mudah untuk mulai belajar dan menguasai keterampilan menulis artikel & editorial jurnal.",
      steps: [
        {
          icon: "📚",
          title: "Daftar & Pilih Pelatihan",
          description: "Mulai dengan membuat akun dan pilih pelatihan yang sesuai kebutuhan Anda.",
        },
        {
          icon: "🧠",
          title: "Ikuti Materi Interaktif",
          description: "Belajar lewat video, materi teks, quiz, serta ikut absensi saat sesi meet berlangsung.",
        },
        {
          icon: "⭐",
          title: "Evaluasi & Publikasi",
          description:
            "Selesaikan tugas akhir, dapatkan sertifikat, dan siap mengaplikasikan ke jurnal ilmiah OJS.",
        },
        {
          icon: "📈",
          title: "Terbitkan Artikel",
          description: "Gunakan hasil pembelajaran Anda untuk publikasi di jurnal ilmiah terpercaya.",
        },
      ],
    },
    availability: {
      title: "Tersedia 24/7 untuk Kebutuhan Belajar Anda",
      description:
        "Akses semua materi pelatihan tanpa batasan waktu. Cocok untuk dosen, guru, mahasiswa, hingga praktisi yang ingin meningkatkan keterampilan menulis artikel dan mengelola jurnal ilmiah.",
      cta: "Gabung Sekarang",
      imageAlt: "Peserta Pelatihan",
    },
    features: [
      {
        icon: "🎬",
        title: "Video Interaktif",
        description: "Belajar lewat tayangan materi yang jelas dan terarah.",
      },
      {
        icon: "🧩",
        title: "Quiz & Evaluasi",
        description: "Uji pemahaman Anda dengan quiz dan soal latihan.",
      },
      {
        icon: "📅",
        title: "Meet & Absensi",
        description: "Ikuti kelas online dengan sistem absensi otomatis.",
      },
      {
        icon: "📘",
        title: "Materi Pembelajaran",
        description: "Modul PDF, artikel contoh, dan panduan OJS tersedia untuk semua peserta.",
      },
    ],
    footer: {
      copyright: "© 2025 NesabaLearn. Semua Hak Dilindungi.",
      columns: [
        { heading: "Tentang Kami", items: ["Profil", "Visi & Misi", "Tim"] },
        { heading: "Pelatihan", items: ["Program Artikel Ilmiah", "Program Editorial OJS", "Sertifikasi"] },
        { heading: "Bantuan", items: ["Hubungi Kami", "FAQ", "Kebijakan Privasi"] },
        { heading: "Sosial Media", items: ["@PkmNesaba"] },
      ],
    },
  },
  en: {
    brandName: "Nesaba Learn",
    nav: {
      login: "Login",
      signUp: "Sign Up",
      languageToggle: "Switch Language",
    },
    auth: {
      login: {
        title: "Log in to your account",
        subtitle: "Enter your email and password below to log in",
        emailLabel: "Email",
        emailPlaceholder: "Enter your email",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter your password",
        forgotPassword: "Forgot password?",
        submit: "Login",
        footer: "Don't have an account?",
        footerLink: "Sign up",
      },
      register: {
        title: "Create your account",
        subtitle: "Enter your details below to sign up",
        firstNameLabel: "First name",
        firstNamePlaceholder: "Enter your first name",
        lastNameLabel: "Last name",
        lastNamePlaceholder: "Enter your last name",
        emailLabel: "Email",
        emailPlaceholder: "Enter your email",
        passwordLabel: "Password",
        passwordPlaceholder: "Create a password",
        confirmPasswordLabel: "Confirm password",
        confirmPasswordPlaceholder: "Confirm your password",
        submit: "Register",
        footer: "Already have an account?",
        footerLink: "Log in",
      },
      forgot: {
        title: "Forgot your password?",
        subtitle: "Enter your email address and we will send a reset link",
        emailLabel: "Email",
        emailPlaceholder: "Enter your email",
        submit: "Send Reset Link",
        submitBusy: "Sending...",
        footer: "Remember your password?",
        footerLink: "Log in",
      },
    },
    hero: {
      title: ["The Premier Learning Platform", "for Academic Articles & Journals"],
      description:
        "Upgrade your academic writing skills and manage OJS journals through a modern learning platform. Study anywhere, anytime with videos, quizzes, live meetings, attendance, and interactive materials.",
      cta: "Start Learning Now",
      imageAlt: "Online Learning",
    },
    overview: {
      title: "Academic Article & Journal Learning Made Simple",
      description:
        "NesabaLearn delivers an interactive LMS to help writers, lecturers, teachers, and students master the workflow of article writing, journal publication, and OJS management. Every module is structured, easy to digest, and paired with comprehensive digital tools.",
      cta: "Browse Training Programs",
    },
    howItWorks: {
      title: "How to Use NesabaLearn",
      description:
        "Follow these quick steps to begin learning and mastering academic & editorial writing.",
      steps: [
        {
          icon: "📚",
          title: "Register & Pick a Course",
          description: "Create your account and choose the training that matches your goals.",
        },
        {
          icon: "🧠",
          title: "Join Interactive Modules",
          description: "Learn through videos, reading materials, quizzes, and track attendance in live sessions.",
        },
        {
          icon: "⭐",
          title: "Evaluate & Publish",
          description:
            "Complete the final project, earn your certificate, and get ready to apply it within OJS journals.",
        },
        {
          icon: "📈",
          title: "Publish Your Article",
          description: "Use your new skills to publish in reputable academic journals.",
        },
      ],
    },
    availability: {
      title: "Available 24/7 for Your Learning Needs",
      description:
        "Access every module without time limits. Perfect for lecturers, teachers, students, and professionals seeking to sharpen their writing and journal management skills.",
      cta: "Join Today",
      imageAlt: "Training Participants",
    },
    features: [
      {
        icon: "🎬",
        title: "Interactive Videos",
        description: "Learn through clear and guided learning sessions.",
      },
      {
        icon: "🧩",
        title: "Quizzes & Evaluation",
        description: "Test your understanding with quizzes and practice questions.",
      },
      {
        icon: "📅",
        title: "Live Meets & Attendance",
        description: "Join online classes with built-in attendance tracking.",
      },
      {
        icon: "📘",
        title: "Learning Materials",
        description: "Access PDFs, sample articles, and OJS guides for every participant.",
      },
    ],
    footer: {
      copyright: "© 2025 NesabaLearn. All Rights Reserved.",
      columns: [
        { heading: "About Us", items: ["Profile", "Vision & Mission", "Team"] },
        { heading: "Training", items: ["Scientific Article Program", "OJS Editorial Program", "Certification"] },
        { heading: "Support", items: ["Contact Us", "FAQ", "Privacy Policy"] },
        { heading: "Social Media", items: ["@PkmNesaba"] },
      ],
    },
  },
};

export const availableLanguages = [
  { code: "id", label: "Bahasa Indonesia" },
  { code: "en", label: "English" },
];

const adminTranslations = {
  id: {
    common: {
      home: "Beranda",
      meetings: "Pertemuan",
      users: "Pengguna",
      back: "Kembali",
      cancel: "Batal",
      save: "Simpan",
      saveChanges: "Simpan Perubahan",
    },
    topbar: {
      adminLabel: "Admin",
      userLabel: "Pengguna",
      profile: "Profil",
      changePassword: "Ganti Password",
      settings: "Pengaturan",
      logout: "Keluar",
      languageToggleAria: "Ganti bahasa",
      themeToggleToLight: "Ubah ke mode terang",
      themeToggleToDark: "Ubah ke mode gelap",
    },
    sidebar: {
      close: "Tutup menu",
      links: {
        dashboard: "Dashboard",
        meetings: "Pertemuan",
        users: "Pengguna",
        profile: "Profil",
        password: "Password",
      },
    },
    dashboard: {
      title: "Dashboard",
      subtitle: "Pantau perkembangan komunitas NesabaLearn.",
      stats: {
        totalUsers: { title: "Total Pengguna", note: "Termasuk mentor & siswa" },
        meetings: { title: "Meeting Bulan Ini", note: "Terjadwal di kalender" },
        attendance: { title: "Tingkat Kehadiran", note: "Meeting terselenggara" },
      },
      quickActions: {
        addMeeting: { label: "Tambah Pertemuan", description: "Jadwalkan agenda baru" },
        inviteUser: { label: "Tambahkan Pengguna", description: "Kirim undangan belajar" },
        viewReport: { label: "Lihat Laporan", description: "Pantau performa program" },
      },
      growth: {
        title: "Tren Pertumbuhan",
        description: "Perbandingan penambahan pengguna dan meeting selama 6 bulan terakhir.",
        legendUsers: "Pengguna",
        legendMeetings: "Pertemuan",
      },
      status: {
        title: "Status Kehadiran",
        description: "{{completed}} pertemuan selesai dari total {{total}}.",
        completed: "Terlaksana",
        cancelled: "Dibatalkan",
        upcoming: "Akan Datang",
      },
      alerts: {
        title: "Pemberitahuan Terbaru",
        updated: "Terakhir diperbarui {{time}} lalu",
        badges: {
          meeting: "Pertemuan",
          reminder: "Pengingat",
          info: "Info",
        },
      },
      notes: {
        title: "Catatan Admin",
        description: "Gunakan shortcut di bawah ini untuk aksi cepat.",
        shortcutHint: "Lihat semua catatan",
      },
    },
    usersPage: {
      title: "Pengguna",
      description: "Kelola semua pengguna yang terdaftar di sistem.",
      addButton: "+ Tambah Pengguna",
      table: {
        name: "NAMA",
        email: "EMAIL",
        role: "ROLE",
        actions: "AKSI",
      },
        view: "Lihat detail pengguna",
        edit: "Edit pengguna",
        impersonate: "Masuk sebagai pengguna",
        remove: "Hapus pengguna",
      },
    userForm: {
      create: {
        title: "Tambah Pengguna",
        description: "Masukkan data pengguna baru seperti nama, email, password, dan role.",
        submit: "Simpan Pengguna",
      },
      edit: {
        title: "Edit Pengguna",
        description: "Perbarui informasi pengguna seperti nama, email, role, dan status.",
        submit: "Simpan Perubahan",
      },
      fields: {
        name: "Nama",
        email: "Email",
        password: "Password",
        confirmPassword: "Konfirmasi Password",
        role: "Role",
      },
      placeholders: {
        name: "Masukkan nama",
        email: "Masukkan email",
        password: "Masukkan password",
        confirmPassword: "Konfirmasi password",
      },
      roles: {
        admin: "Admin",
        user: "Pengguna",
      },
    },
    userDetail: {
      pageTitle: "Detail Pengguna",
      notFound: "Pengguna tidak ditemukan.",
      lastLoginEmpty: "Belum pernah login",
      header: {
        edit: "Edit Pengguna",
        resetPassword: "Reset Password",
      },
      infoSection: {
        title: "Informasi Pengguna",
        description: "Detail lengkap mengenai akun dan kontak pengguna.",
        labels: {
          name: "Nama Lengkap",
          email: "Email",
          role: "Peran",
          status: "Status Akun",
          joined: "Tanggal Bergabung",
          lastActivity: "Terakhir Aktivitas",
        },
      },
      accessSection: {
        title: "Akses & Keamanan",
        description: "Kelola tingkat akses pengguna serta riwayat keamanan.",
        accessLabel: "Hak Akses",
        advice: "Atur ulang peran melalui tombol edit.",
        historyLabel: "Riwayat Keamanan",
        historyList: [
          "Terakhir login: {{lastLogin}}",
          "Perangkat terakhir: Web Browser",
          "Status verifikasi email: Aktif",
        ],
      },
      activitySection: {
        title: "Aktivitas Terkini",
        description: "Ringkasan aktivitas terbaru pengguna di platform.",
        viewAll: "Lihat Semua",
        items: {
          dashboard: "Mengakses Dashboard",
          download: "Mengunduh materi terbaru",
          mentoring: "Berpartisipasi pada mentoring",
          dashboardDesc: "Login terakhir dicatat pada {{lastLogin}}",
          downloadDesc: "Belum ada data aktual, sambungkan ke API Anda.",
          mentoringDesc: "Tambahkan log aktivitas riil dari backend.",
        },
      },
    },
    profilePage: {
      title: "Profil Pengguna",
      description: "Kelola informasi akun dan foto profil Anda agar selalu terbaru.",
      back: "Kembali",
      save: "Simpan Perubahan",
      nameLabel: "Nama Lengkap",
      emailLabel: "Email",
      namePlaceholder: "Masukkan nama lengkap",
      emailPlaceholder: "Masukkan email aktif",
      chooseFile: "Pilih Berkas",
      fileHint: "Format gambar JPG atau PNG, ukuran maksimal 3 MB.",
      passwordCta: "Ganti Password",
      success: "Perubahan berhasil disimpan.",
      notFound: "Tidak dapat menemukan data pengguna aktif.",
      error: "Terjadi kesalahan saat menyimpan profil.",
    },
    changePassword: {
      title: "Ganti Password",
      description: "Untuk keamanan, gunakan kombinasi huruf, angka, dan simbol yang unik.",
      fields: {
        current: "Password Lama",
        new: "Password Baru",
        confirm: "Ulangi Password Baru",
      },
      placeholders: {
        current: "Masukkan password saat ini",
        new: "Masukkan password baru",
        confirm: "Ulangi password baru",
      },
      errors: {
        blank: "Semua kolom wajib diisi.",
        minLength: "Password baru minimal 6 karakter.",
        mismatch: "Konfirmasi password tidak cocok.",
        noUser: "Tidak ada pengguna yang sedang login.",
        wrongCurrent: "Password lama tidak sesuai.",
        general: "Terjadi kesalahan saat mengubah password.",
      },
      success: "Password berhasil diperbarui.",
      back: "Kembali",
      submit: "Ganti Password",
    },
    meetingList: {
      title: "Pertemuan",
      description: "Kelola semua jadwal pertemuan Anda di satu tempat.",
      addButton: "+ Tambah Pertemuan",
      filterAll: "Semua",
      filterArticle: "Artikel",
      filterEditorial: "Editorial",
      table: {
        title: "JUDUL",
        date: "TANGGAL PERTEMUAN",
        start: "WAKTU MULAI",
        end: "WAKTU SELESAI",
        url: "TAUTAN PERTEMUAN",
        actions: "AKSI",
      },
      join: "Gabung Pertemuan",
    },
    meetingDetail: {
      pageTitle: "Detail Pertemuan",
      description: "Halaman ini menampilkan informasi lengkap tentang pertemuan, termasuk waktu, deskripsi, dan lampiran.",
      notFound: "Pertemuan tidak ditemukan.",
      noDescription: "Belum ada deskripsi.",
      infoTitle: "Informasi Pertemuan",
      attachmentsTitle: "Lampiran Pertemuan",
      attachmentsDelete: "Hapus",
      attachmentsView: "Lihat",
      attachmentsConfirm: "Hapus lampiran ini?",
      noAttachments: "Tidak ada lampiran untuk pertemuan ini.",
      materialTitle: "Materi Pertemuan",
      materialTypeContent: "Konten",
      materialTypeVideo: "Video",
      materialDelete: "Hapus",
      materialView: "Lihat",
      materialConfirm: "Hapus materi ini?",
      noMaterials: "Belum ada materi untuk pertemuan ini.",
      materialCTA: "+ Tambah Materi",
      attendanceTitle: "Absensi Pertemuan",
      attendanceNotOpen: "Absensi meeting belum dibuka.",
      attendanceOpenAt: "Dibuka pada {{date}}",
      noAttendance: "Belum ada absensi di pertemuan ini.",
      taskTitle: "Tugas Pertemuan",
      taskDescription: "Instruksi dan lampiran tugas untuk pertemuan ini.",
      taskAdd: "+ Tambah Tugas",
      taskEdit: "Edit Tugas",
      taskDelete: "Hapus Tugas",
      taskConfirm: "Hapus tugas pertemuan ini?",
      taskEmpty: "Belum ada tugas untuk pertemuan ini.",
      taskType: "Tipe Tugas",
      taskContent: "Konten Tugas",
      taskFile: "Lampiran Tugas",
      taskStart: "Dibuka",
      taskEnd: "Deadline",
      taskSchedule: "Jadwal Tugas",
      taskDownload: "Unduh Lampiran",
      taskNotOpen: "Tugas belum dibuka.",
      taskClosed: "Tugas sudah ditutup.",
      assignmentTitle: "Pengumpulan Tugas Pertemuan",
      assignmentDescription:
        "Kumpulkan tugas pertemuan dalam bentuk file (PDF, Word, PPT, ZIP, video, dll) agar mentor dapat melakukan penilaian.",
      assignmentCTA: "Daftar Pengumpulan Tugas",
      assignmentEmpty: "Belum ada pengumpulan tugas untuk pertemuan ini.",
      assignmentListTitle: "Daftar Pengumpulan Tugas",
      assignmentReviewCta: "Beri Nilai",
      assignmentReviewEdit: "Edit Nilai",
      assignmentReviewPending: "Menunggu penilaian",
      assignmentReviewDone: "Sudah dinilai",
      assignmentReviewTitle: "Penilaian Tugas",
      assignmentReviewDescription: "Nilai pengumpulan tugas dari peserta pertemuan.",
      assignmentReviewRubric: "Rubrik Penilaian",
      assignmentReviewAdd: "+ Tambah Kriteria",
      assignmentReviewCriterion: "Kriteria",
      assignmentReviewScore: "Skor",
      assignmentReviewMax: "Skor Maks",
      assignmentReviewFeedback: "Komentar Mentor",
      assignmentReviewSave: "Simpan Penilaian",
      assignmentReviewTotal: "Total Skor",
      assignmentReviewEmpty: "Belum ada feedback dari mentor.",
      quizTitle: "Quiz Pertemuan",
      quizCTA: "+ Tambah Quiz",
      quizDelete: "Hapus",
      quizConfirm: "Hapus quiz ini?",
      quizEmpty: "Belum ada quiz untuk pertemuan ini.",
      historyTitle: "Riwayat Quiz Attempt",
      historyEmpty: "Belum ada quiz attempt untuk pertemuan ini.",
      editButton: "Edit Pertemuan",
      labels: {
        title: "Judul Pertemuan",
        description: "Deskripsi",
        link: "Link Pertemuan",
        type: "Tipe Pertemuan",
        date: "Tanggal Pertemuan",
        time: "Waktu Pertemuan",
      },
    },
    meetingForm: {
      create: {
        title: "Tambah Pertemuan",
        description: "Buat jadwal pertemuan baru dengan mengisi informasi seperti judul, URL, waktu, deskripsi, dan lampiran.",
        submit: "Tambah Pertemuan",
      },
      edit: {
        title: "Edit Pertemuan",
        description: "Ubah informasi pertemuan seperti judul, URL, waktu pelaksanaan, deskripsi, dan lampiran.",
        submit: "Simpan Perubahan",
      },
      fields: {
        title: "Judul Pertemuan",
        type: "Tipe Pertemuan",
        url: "URL Pertemuan",
        date: "Tanggal Pertemuan",
        start: "Waktu Mulai",
        end: "Waktu Selesai",
        description: "Deskripsi Pertemuan",
        attachments: "Lampiran Baru",
        materials: "Materi Pertemuan",
      },
      placeholders: {
        title: "Masukkan judul pertemuan",
        url: "Masukkan URL pertemuan",
        date: "Pilih tanggal pertemuan",
        start: "Pilih waktu mulai",
        end: "Pilih waktu selesai",
        description: "Tuliskan agenda atau catatan penting.",
      },
      attachmentHint: "Format yang didukung: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, JPG, JPEG, PNG. Maksimal 10MB per file.",
      materialHint: "Format yang didukung: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, JPG, JPEG, PNG. Maksimal 10MB per file.",
      filePicker: {
        button: "Pilih Berkas",
        empty: "Belum ada file yang dipilih",
        count: "{{count}} file dipilih",
      },
    },
    materialForm: {
      title: "Tambah Materi Pertemuan",
      description: 'Halaman ini digunakan untuk menambahkan materi meeting baru untuk "{{title}}".',
      typeLabel: "Tipe Materi",
      nameLabel: "Nama Materi",
      contentLabel: "Konten Materi",
      videoLabel: "File Video",
      chooseFile: "Pilih Berkas",
      noFile: "Belum ada file yang dipilih",
      formatHint: "Format yang didukung: Mp4, WebM, Ogg, MOV.",
      back: "Kembali",
      submit: "Simpan",
    },
    assignmentForm: {
      title: "Tambah Tugas Pertemuan",
      description: 'Halaman ini digunakan untuk menambahkan tugas meeting untuk "{{title}}".',
      typeLabel: "Tipe Tugas",
      nameLabel: "Judul Tugas",
      contentLabel: "Konten Tugas",
      fileLabel: "File Tugas",
      chooseFile: "Pilih Berkas",
      noFile: "Belum ada file yang dipilih",
      formatHint: "Format file bebas, maksimal 50MB.",
      startTime: "Dibuka",
      endTime: "Deadline",
      back: "Kembali",
      submit: "Simpan Tugas",
    },
    quizForm: {
      title: "Tambah Quiz",
      description: 'Halaman ini digunakan untuk membuat quiz baru untuk pertemuan "{{title}}".',
      info: {
        name: "Judul Quiz",
        description: "Deskripsi",
        minScore: "Skor Minimum",
        timeLimit: "Batas Waktu (menit)",
        startTime: "Waktu Mulai Quiz",
        endTime: "Deadline Quiz",
      },
      questions: {
        title: "Pertanyaan Quiz",
        description: "Kelola daftar pertanyaan untuk quiz ini.",
        addButton: "+ Tambah Pertanyaan",
        questionLabel: "Pertanyaan",
        typeLabel: "Tipe Pertanyaan",
        scoreLabel: "Skor",
        optionsLabel: "Pilihan Jawaban",
        addOption: "+ Tambah Pilihan",
        optionPlaceholder: "Masukkan pilihan jawaban",
        remove: "Hapus",
        essayLabel: "Jawaban Esai",
      },
      buttons: {
        cancel: "Batal",
        save: "Simpan Quiz",
      },
    },
  },
  en: {
    common: {
      home: "Home",
      meetings: "Meetings",
      users: "Users",
      back: "Back",
      cancel: "Cancel",
      save: "Save",
      saveChanges: "Save Changes",
    },
    topbar: {
      adminLabel: "Admin",
      userLabel: "User",
      profile: "Profile",
      changePassword: "Change Password",
      settings: "Settings",
      logout: "Logout",
      languageToggleAria: "Switch language",
      themeToggleToLight: "Switch to light mode",
      themeToggleToDark: "Switch to dark mode",
    },
    sidebar: {
      close: "Close menu",
      links: {
        dashboard: "Dashboard",
        meetings: "Meetings",
        users: "Users",
        profile: "Profile",
        password: "Password",
      },
    },
    dashboard: {
      title: "Dashboard",
      subtitle: "Track NesabaLearn community progress.",
      stats: {
        totalUsers: { title: "Total Users", note: "Includes mentors & students" },
        meetings: { title: "Meetings This Month", note: "Scheduled on the calendar" },
        attendance: { title: "Attendance Rate", note: "Meetings conducted" },
      },
      quickActions: {
        addMeeting: { label: "Add Meeting", description: "Schedule a new agenda" },
        inviteUser: { label: "Add User", description: "Send a learning invite" },
        viewReport: { label: "View Reports", description: "Monitor program performance" },
      },
      growth: {
        title: "Growth Trend",
        description: "Compare user and meeting additions across the last 6 months.",
        legendUsers: "Users",
        legendMeetings: "Meetings",
      },
      status: {
        title: "Attendance Status",
        description: "{{completed}} meetings finished out of {{total}} total.",
        completed: "Completed",
        cancelled: "Cancelled",
        upcoming: "Upcoming",
      },
      alerts: {
        title: "Latest Notifications",
        updated: "Last updated {{time}} ago",
        badges: {
          meeting: "Meeting",
          reminder: "Reminder",
          info: "Info",
        },
      },
      notes: {
        title: "Admin Notes",
        description: "Use the shortcuts below for quick actions.",
        shortcutHint: "View all notes",
      },
    },
    usersPage: {
      title: "Users",
      description: "Manage every user registered in the system.",
      addButton: "+ Add User",
      table: {
        name: "NAME",
        email: "EMAIL",
        role: "ROLE",
        actions: "ACTIONS",
      },
        view: "View user detail",
        edit: "Edit user",
        impersonate: "Login as user",
        remove: "Remove user",
      },
    userForm: {
      create: {
        title: "Add User",
        description: "Fill in the new user's name, email, password, and role.",
        submit: "Save User",
      },
      edit: {
        title: "Edit User",
        description: "Update the user's name, email, role, or status.",
        submit: "Save Changes",
      },
      fields: {
        name: "Name",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm Password",
        role: "Role",
      },
      placeholders: {
        name: "Enter name",
        email: "Enter email",
        password: "Enter password",
        confirmPassword: "Confirm password",
      },
      roles: {
        admin: "Admin",
        user: "User",
      },
    },
    userDetail: {
      pageTitle: "User Detail",
      notFound: "User not found.",
      lastLoginEmpty: "Never logged in",
      header: {
        edit: "Edit User",
        resetPassword: "Reset Password",
      },
      infoSection: {
        title: "User Information",
        description: "Full details about the account and contact.",
        labels: {
          name: "Full Name",
          email: "Email",
          role: "Role",
          status: "Account Status",
          joined: "Joined Date",
          lastActivity: "Last Activity",
        },
      },
      accessSection: {
        title: "Access & Security",
        description: "Manage access level and security history.",
        accessLabel: "Access Rights",
        advice: "Change the role via the edit button.",
        historyLabel: "Security History",
        historyList: [
          "Last login: {{lastLogin}}",
          "Latest device: Web Browser",
          "Email verification status: Active",
        ],
      },
      activitySection: {
        title: "Recent Activity",
        description: "Latest activity performed on the platform.",
        viewAll: "View All",
        items: {
          dashboard: "Accessed Dashboard",
          download: "Downloaded the latest material",
          mentoring: "Joined a mentoring session",
          dashboardDesc: "Last login recorded on {{lastLogin}}",
          downloadDesc: "No real data yet, connect to your API.",
          mentoringDesc: "Add the real activity log from backend.",
        },
      },
    },
    profilePage: {
      title: "User Profile",
      description: "Manage account info and avatar to keep it up to date.",
      back: "Back",
      save: "Save Changes",
      nameLabel: "Full Name",
      emailLabel: "Email",
      namePlaceholder: "Enter full name",
      emailPlaceholder: "Enter active email",
      chooseFile: "Choose File",
      fileHint: "Use JPG or PNG up to 3 MB.",
      passwordCta: "Change Password",
      success: "Profile updated successfully.",
      notFound: "Unable to find active user data.",
      error: "Something went wrong while saving the profile.",
    },
    changePassword: {
      title: "Change Password",
      description: "Use a unique mix of letters, numbers, and symbols for security.",
      fields: {
        current: "Current Password",
        new: "New Password",
        confirm: "Repeat New Password",
      },
      placeholders: {
        current: "Enter current password",
        new: "Enter new password",
        confirm: "Repeat new password",
      },
      errors: {
        blank: "All fields are required.",
        minLength: "New password must be at least 6 characters.",
        mismatch: "Password confirmation does not match.",
        noUser: "No active user session found.",
        wrongCurrent: "Current password does not match.",
        general: "Failed to change password.",
      },
      success: "Password updated successfully.",
      back: "Back",
      submit: "Change Password",
    },
    meetingList: {
      title: "Meetings",
      description: "Manage every scheduled meeting in one place.",
      addButton: "+ Add Meeting",
      filterAll: "All",
      filterArticle: "Article",
      filterEditorial: "Editorial",
      table: {
        title: "TITLE",
        date: "MEETING DATE",
        start: "START TIME",
        end: "END TIME",
        url: "MEETING URL",
        actions: "ACTIONS",
      },
      join: "Join Meeting",
    },
    meetingDetail: {
      pageTitle: "Meeting Detail",
      description: "This page shows full information about the meeting, including time, description, and attachments.",
      notFound: "Meeting not found.",
      noDescription: "No description provided.",
      infoTitle: "Meeting Information",
      attachmentsTitle: "Meeting Attachments",
      attachmentsDelete: "Delete",
      attachmentsView: "View",
      attachmentsConfirm: "Delete this attachment?",
      noAttachments: "No attachments for this meeting.",
      materialTitle: "Meeting Materials",
      materialTypeContent: "Content",
      materialTypeVideo: "Video",
      materialDelete: "Delete",
      materialView: "View",
      materialConfirm: "Delete this material?",
      noMaterials: "No materials have been added yet.",
      materialCTA: "+ Add Material",
      attendanceTitle: "Meeting Attendance",
      attendanceNotOpen: "Attendance has not opened yet.",
      attendanceOpenAt: "Opens at {{date}}",
      noAttendance: "No attendance records for this meeting.",
      taskTitle: "Meeting Task",
      taskDescription: "Instructions and attachments for this meeting task.",
      taskAdd: "+ Add Task",
      taskEdit: "Edit Task",
      taskDelete: "Delete Task",
      taskConfirm: "Delete this meeting task?",
      taskEmpty: "No tasks for this meeting yet.",
      taskType: "Task Type",
      taskContent: "Task Content",
      taskFile: "Task Attachment",
      taskStart: "Opens",
      taskEnd: "Deadline",
      taskSchedule: "Task Schedule",
      taskDownload: "Download Attachment",
      taskNotOpen: "Task has not opened yet.",
      taskClosed: "Task has been closed.",
      assignmentTitle: "Meeting Task Submissions",
      assignmentDescription:
        "Collect meeting assignments in file formats (PDF, Word, PPT, ZIP, video, etc.) so mentors can evaluate them.",
      assignmentCTA: "Assignment Submissions",
      assignmentEmpty: "No assignment submissions for this meeting.",
      assignmentListTitle: "Assignment Submissions",
      assignmentReviewCta: "Grade",
      assignmentReviewEdit: "Edit Grade",
      assignmentReviewPending: "Waiting for review",
      assignmentReviewDone: "Reviewed",
      assignmentReviewTitle: "Assignment Review",
      assignmentReviewDescription: "Assess each task submission from meeting participants.",
      assignmentReviewRubric: "Scoring Rubric",
      assignmentReviewAdd: "+ Add Criterion",
      assignmentReviewCriterion: "Criterion",
      assignmentReviewScore: "Score",
      assignmentReviewMax: "Max Score",
      assignmentReviewFeedback: "Mentor Feedback",
      assignmentReviewSave: "Save Review",
      assignmentReviewTotal: "Total Score",
      assignmentReviewEmpty: "No mentor feedback yet.",
      quizTitle: "Meeting Quiz",
      quizCTA: "+ Add Quiz",
      quizDelete: "Delete",
      quizConfirm: "Delete this quiz?",
      quizEmpty: "No quiz available for this meeting.",
      historyTitle: "Quiz Attempt History",
      historyEmpty: "No quiz attempts for this meeting.",
      editButton: "Edit Meeting",
      labels: {
        title: "Meeting Title",
        description: "Description",
        link: "Meeting Link",
        type: "Meeting Type",
        date: "Meeting Date",
        time: "Meeting Time",
      },
    },
    meetingForm: {
      create: {
        title: "Add Meeting",
        description: "Create a new meeting by filling the title, URL, time, description, and attachments.",
        submit: "Add Meeting",
      },
      edit: {
        title: "Edit Meeting",
        description: "Update meeting information such as title, URL, schedule, description, and attachments.",
        submit: "Save Changes",
      },
      fields: {
        title: "Meeting Title",
        type: "Meeting Type",
        url: "Meeting URL",
        date: "Meeting Date",
        start: "Start Time",
        end: "End Time",
        description: "Meeting Description",
        attachments: "New Attachments",
        materials: "Meeting Materials",
      },
      placeholders: {
        title: "Enter meeting title",
        url: "Enter meeting URL",
        date: "Choose meeting date",
        start: "Choose start time",
        end: "Choose end time",
        description: "Add agenda or important notes.",
      },
      attachmentHint: "Supported formats: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, JPG, JPEG, PNG. Max 10MB per file.",
      materialHint: "Supported formats: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, JPG, JPEG, PNG. Max 10MB per file.",
      filePicker: {
        button: "Choose Files",
        empty: "No file selected",
        count: "{{count}} file(s) selected",
      },
    },
    materialForm: {
      title: "Add Meeting Material",
      description: 'Use this page to add new material for "{{title}}".',
      typeLabel: "Material Type",
      nameLabel: "Material Name",
      contentLabel: "Material Content",
      videoLabel: "Video File",
      chooseFile: "Choose File",
      noFile: "No file chosen",
      formatHint: "Supported formats: Mp4, WebM, Ogg, MOV.",
      back: "Back",
      submit: "Save",
    },
    assignmentForm: {
      title: "Add Meeting Task",
      description: 'Use this page to add a task for "{{title}}".',
      typeLabel: "Task Type",
      nameLabel: "Task Title",
      contentLabel: "Task Content",
      fileLabel: "Task File",
      chooseFile: "Choose File",
      noFile: "No file chosen",
      formatHint: "Any file type, max 50MB.",
      startTime: "Opens At",
      endTime: "Deadline",
      back: "Back",
      submit: "Save Task",
    },
    quizForm: {
      title: "Add Quiz",
      description: 'Create a new quiz for "{{title}}".',
      info: {
        name: "Quiz Title",
        description: "Description",
        minScore: "Minimum Score",
        timeLimit: "Time Limit (minutes)",
        startTime: "Quiz Opens At",
        endTime: "Quiz Deadline",
      },
      questions: {
        title: "Quiz Questions",
        description: "Manage all questions for this quiz.",
        addButton: "+ Add Question",
        questionLabel: "Question",
        typeLabel: "Question Type",
        scoreLabel: "Score",
        optionsLabel: "Answer Choices",
        addOption: "+ Add Choice",
        optionPlaceholder: "Enter answer choice",
        remove: "Remove",
        essayLabel: "Essay Answer",
      },
      buttons: {
        cancel: "Cancel",
        save: "Save Quiz",
      },
    },
  },
};

export const LanguageContext = createContext({
  language: "id",
  setLanguage: () => {},
  toggleLanguage: () => {},
  copy: translations.id,
  adminCopy: adminTranslations.id,
  availableLanguages,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window === "undefined") {
      return "id";
    }
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return stored && translations[stored] ? stored : "id";
  });

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  const toggleLanguage = useCallback(
    () => setLanguage((prev) => (prev === "id" ? "en" : "id")),
    []
  );

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      toggleLanguage,
      copy: translations[language],
      adminCopy: adminTranslations[language],
      availableLanguages,
    }),
    [language, toggleLanguage]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
